# These are supported funding model platforms

github: SEOSiri-Official
custom: ['https://github.com/sponsors/SEOSiri-Official', 'mailto:badhan_pbn@yahoo.com?subject=Enterprise%20Sponsorship%20Inquiry']
