import React, { useState } from 'react';
import { 
  BookOpen, 
  Terminal, 
  Copy, 
  Check, 
  Download, 
  Search, 
  ExternalLink, 
  Sparkles, 
  ShieldCheck, 
  Zap, 
  CheckCircle2, 
  Code, 
  Globe, 
  Layers, 
  Server,
  FileCode2,
  Mail,
  ChevronRight,
  Info,
  Box,
  Cpu
} from 'lucide-react';
import { MCP_MODULES, LEAD_ARCHITECT, OFFICIAL_CORPORATE_EMAIL, DEVELOPERS_SUBDOMAIN, TOTAL_MCP_TOOLS_COUNT, OFFICIAL_EDGE_GATEWAYS } from '../data/mcpData';
import { MCPModule } from '../types';

interface DocumentationViewerProps {
  initialModuleId?: string;
}

export const DocumentationViewer: React.FC<DocumentationViewerProps> = ({ initialModuleId }) => {
  const [selectedModuleId, setSelectedModuleId] = useState<string>(
    initialModuleId || MCP_MODULES[0].id
  );
  const [searchQuery, setSearchQuery] = useState('');
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'quickstart' | 'tools' | 'config' | 'edge' | 'gateways'>('quickstart');

  const selectedModule = MCP_MODULES.find((m) => m.id === selectedModuleId) || MCP_MODULES[0];

  const handleCopy = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const handleDownloadMarkdown = (module: MCPModule) => {
    const mdContent = `# ${module.title} (${module.pypiPackage})
> Official Documentation & Integration Guide
> Lead Architect: Momenul Ahmad (SEOSiri Enterprise Labs)
> Official Corporate Desk: ${OFFICIAL_CORPORATE_EMAIL}
> Developer Portal Hub: ${DEVELOPERS_SUBDOMAIN}
> Module Dedicated Edge Gateway: ${module.edgeUrl}

## Package Identity
- **PyPI Package**: \`${module.pypiPackage}\`
- **Current Version**: \`v${module.version}\`
- **Status**: ${module.status}
- **Category**: ${module.category}
- **Guide**: ${module.guideUrl}

## Description
${module.description}

## Installation Command
\`\`\`bash
${module.pypiCommand}
\`\`\`

## Claude Desktop / Cursor AI Configuration (\`claude_desktop_config.json\`)
\`\`\`json
{
  "mcpServers": {
    "${module.id}": {
      "command": "uvx",
      "args": ["${module.pypiPackage}"],
      "env": {
        ${(module.envVars || []).map((v) => `"${v}": "YOUR_${v}"`).join(',\n        ')}
      }
    }
  }
}
\`\`\`

## Exact Module Edge Gateway SSE Endpoint
- **Exact Gateway Host**: \`${module.edgeGateway}\`
- **Exact Gateway SSE URL**: \`${module.edgeUrl}\`
- **Protocol**: Standard JSON-RPC 2.0 over Server-Sent Events

## Tools Reference (${module.tools.length} Tools)
${module.tools.map((tool, idx) => `
### ${idx + 1}. \`${tool.name}\`
${tool.description}

**Sample Input Payload**:
\`\`\`json
${tool.sampleInput}
\`\`\`
`).join('\n')}

---
*Generated by SEOSiri Developer Hub (${DEVELOPERS_SUBDOMAIN}). Direct questions to ${OFFICIAL_CORPORATE_EMAIL}.*
`;

    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${module.pypiPackage}-docs.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const filteredModules = MCP_MODULES.filter((m) => {
    const q = searchQuery.toLowerCase();
    return (
      !searchQuery ||
      m.title.toLowerCase().includes(q) ||
      m.pypiPackage.toLowerCase().includes(q) ||
      m.description.toLowerCase().includes(q) ||
      m.tools.some((t) => t.name.toLowerCase().includes(q))
    );
  });

  const claudeConfigJson = JSON.stringify(
    {
      mcpServers: {
        [selectedModule.id]: {
          command: 'uvx',
          args: [selectedModule.pypiPackage],
          env: (selectedModule.envVars || []).reduce((acc: any, key: string) => {
            acc[key] = `YOUR_${key}`;
            return acc;
          }, {})
        }
      }
    },
    null,
    2
  );

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      {/* Top Banner Header */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 sm:p-8 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl pointer-events-none" />
        
        <div className="relative z-10 flex flex-col md:flex-row md:items-center md:justify-between gap-6">
          <div className="space-y-2 max-w-3xl">
            <div className="flex items-center space-x-2 text-xs font-mono">
              <span className="px-2.5 py-1 rounded-full bg-blue-500/10 border border-blue-500/30 text-blue-400 font-semibold flex items-center gap-1.5">
                <BookOpen className="w-3.5 h-3.5" />
                Dedicated Documentation Assets
              </span>
              <span className="text-slate-400">15 PyPI Packages • {TOTAL_MCP_TOOLS_COUNT} Tools • 10 Live Edge Gateways</span>
            </div>

            <h2 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
              SEOSiri Model Context Protocol Documentation Hub
            </h2>
            <p className="text-sm text-slate-300 leading-relaxed">
              Complete, production-ready documentation for all 15 official SEOSiri PyPI packages and {TOTAL_MCP_TOOLS_COUNT} specialized MCP tools. Connect locally via <code className="bg-slate-950 px-1.5 py-0.5 rounded text-cyan-300 font-mono text-xs">uvx</code> or through each module's configured edge gateway (e.g. <code className="bg-slate-950 px-1.5 py-0.5 rounded text-amber-300 font-mono text-xs">aeo.seosiri.com</code>, <code className="bg-slate-950 px-1.5 py-0.5 rounded text-amber-300 font-mono text-xs">schema.seosiri.com</code>).
            </p>
          </div>

          <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 flex-shrink-0">
            <button
              onClick={() => handleDownloadMarkdown(selectedModule)}
              className="px-4 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-bold transition-all flex items-center justify-center space-x-2 shadow-lg shadow-blue-500/20"
            >
              <Download className="w-4 h-4" />
              <span>Download Documentation Markdown</span>
            </button>
            <a
              href={selectedModule.guideUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="px-4 py-2.5 bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 rounded-xl text-xs font-bold transition-all flex items-center justify-center space-x-2"
            >
              <ExternalLink className="w-4 h-4 text-emerald-400" />
              <span>SEOSiri Deep-Dive Guide</span>
            </a>
          </div>
        </div>
      </div>

      {/* Main Grid: Sidebar Navigator + Dedicated Asset Viewer */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Left Sidebar: Sticky Package Selector */}
        <div className="lg:col-span-4 space-y-4 lg:sticky lg:top-20">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-bold text-slate-200 uppercase tracking-wider font-mono flex items-center gap-2">
                <Box className="w-4 h-4 text-blue-400" />
                PyPI MCP Directory ({MCP_MODULES.length})
              </h3>
              <span className="text-[10px] font-mono text-emerald-400">{TOTAL_MCP_TOOLS_COUNT} Tools Total</span>
            </div>

            {/* Search Input */}
            <div className="relative">
              <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-2.5" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search packages or tools..."
                className="w-full bg-slate-950 border border-slate-800 rounded-xl pl-9 pr-3 py-2 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-blue-500 transition-all"
              />
            </div>

            {/* List of Modules */}
            <div className="space-y-1.5 max-h-[600px] overflow-y-auto pr-1">
              {filteredModules.map((module) => {
                const isSelected = module.id === selectedModule.id;
                return (
                  <button
                    key={module.id}
                    onClick={() => setSelectedModuleId(module.id)}
                    className={`w-full text-left p-3 rounded-xl transition-all border flex items-center justify-between gap-2 group ${
                      isSelected
                        ? 'bg-blue-950/40 border-blue-500/50 text-white shadow-lg shadow-blue-500/10'
                        : 'bg-slate-950/60 border-slate-800/80 hover:bg-slate-800/60 text-slate-300'
                    }`}
                  >
                    <div className="space-y-0.5 min-w-0">
                      <div className="flex items-center space-x-2">
                        <span className="font-bold text-xs truncate group-hover:text-blue-400 transition-colors">
                          {module.title}
                        </span>
                      </div>
                      <div className="text-[10px] font-mono text-slate-400 truncate">
                        {module.pypiPackage}
                      </div>
                    </div>
                    <div className="flex items-center space-x-2 flex-shrink-0">
                      <span className="px-1.5 py-0.5 rounded text-[10px] font-mono bg-slate-900 border border-slate-700 text-amber-300 font-bold">
                        {module.tools.length} tools
                      </span>
                      <ChevronRight className={`w-3.5 h-3.5 transition-transform ${isSelected ? 'text-blue-400 translate-x-0.5' : 'text-slate-600'}`} />
                    </div>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Quick Corporate Contact Card */}
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 space-y-2 font-mono text-xs text-slate-300">
            <div className="flex items-center space-x-2 text-emerald-400 font-bold">
              <Mail className="w-4 h-4" />
              <span>Official Enterprise Desk</span>
            </div>
            <p className="text-[11px] text-slate-400 leading-relaxed font-sans">
              For enterprise custom deployments or SLA support, email <strong className="text-white">{OFFICIAL_CORPORATE_EMAIL}</strong>.
            </p>
          </div>
        </div>

        {/* Right Area: Dedicated Documentation Content */}
        <div className="lg:col-span-8 space-y-6">
          {/* Header Card for Selected Package */}
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-4">
            <div className="flex flex-wrap items-center justify-between gap-3 pb-4 border-b border-slate-800">
              <div className="space-y-1">
                <div className="flex items-center space-x-2">
                  <span className={`px-2.5 py-0.5 rounded-full text-xs font-mono font-semibold border ${selectedModule.badgeBg} ${selectedModule.badgeText}`}>
                    {selectedModule.pypiPackage}
                  </span>
                  <span className="text-xs font-mono text-slate-400">v{selectedModule.version}</span>
                  <span className="text-xs font-mono text-emerald-400 flex items-center gap-1">
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    {selectedModule.status}
                  </span>
                </div>
                <h2 className="text-2xl font-bold text-white">
                  {selectedModule.title}
                </h2>
              </div>

              <div className="flex items-center space-x-2">
                <button
                  onClick={() => handleCopy(selectedModule.pypiCommand, 'cmd-top')}
                  className="px-3 py-1.5 bg-slate-950 hover:bg-slate-800 border border-slate-700 rounded-lg text-xs font-mono text-slate-200 transition-all flex items-center space-x-1.5"
                >
                  {copiedKey === 'cmd-top' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-slate-400" />}
                  <span>Copy pip command</span>
                </button>
              </div>
            </div>

            <p className="text-sm text-slate-300 leading-relaxed">
              {selectedModule.description}
            </p>

            {/* Navigation Tabs */}
            <div className="flex items-center space-x-2 pt-2 border-b border-slate-800 text-xs font-medium overflow-x-auto">
              <button
                onClick={() => setActiveTab('quickstart')}
                className={`px-4 py-2.5 border-b-2 font-mono transition-all flex items-center space-x-2 whitespace-nowrap ${
                  activeTab === 'quickstart'
                    ? 'border-blue-500 text-blue-400 font-bold'
                    : 'border-transparent text-slate-400 hover:text-slate-200'
                }`}
              >
                <Terminal className="w-3.5 h-3.5" />
                <span>Quickstart & Installation</span>
              </button>
              <button
                onClick={() => setActiveTab('tools')}
                className={`px-4 py-2.5 border-b-2 font-mono transition-all flex items-center space-x-2 whitespace-nowrap ${
                  activeTab === 'tools'
                    ? 'border-blue-500 text-blue-400 font-bold'
                    : 'border-transparent text-slate-400 hover:text-slate-200'
                }`}
              >
                <Cpu className="w-3.5 h-3.5" />
                <span>Tools Spec ({selectedModule.tools.length})</span>
              </button>
              <button
                onClick={() => setActiveTab('config')}
                className={`px-4 py-2.5 border-b-2 font-mono transition-all flex items-center space-x-2 whitespace-nowrap ${
                  activeTab === 'config'
                    ? 'border-blue-500 text-blue-400 font-bold'
                    : 'border-transparent text-slate-400 hover:text-slate-200'
                }`}
              >
                <Code className="w-3.5 h-3.5" />
                <span>JSON-RPC Config</span>
              </button>
              <button
                onClick={() => setActiveTab('edge')}
                className={`px-4 py-2.5 border-b-2 font-mono transition-all flex items-center space-x-2 whitespace-nowrap ${
                  activeTab === 'edge'
                    ? 'border-blue-500 text-blue-400 font-bold'
                    : 'border-transparent text-slate-400 hover:text-slate-200'
                }`}
              >
                <Globe className="w-3.5 h-3.5" />
                <span>Exact Module Gateway</span>
              </button>
              <button
                onClick={() => setActiveTab('gateways')}
                className={`px-4 py-2.5 border-b-2 font-mono transition-all flex items-center space-x-2 whitespace-nowrap ${
                  activeTab === 'gateways'
                    ? 'border-blue-500 text-blue-400 font-bold'
                    : 'border-transparent text-slate-400 hover:text-slate-200'
                }`}
              >
                <Server className="w-3.5 h-3.5 text-amber-400" />
                <span>10 Official Edge Gateways</span>
              </button>
            </div>
          </div>

          {/* TAB 1: Quickstart */}
          {activeTab === 'quickstart' && (
            <div className="space-y-6">
              {/* PyPI Command Box */}
              <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-3">
                <div className="flex items-center justify-between">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300 font-mono flex items-center gap-2">
                    <Terminal className="w-4 h-4 text-emerald-400" />
                    1. PyPI Package Installation
                  </h3>
                  <button
                    onClick={() => handleCopy(selectedModule.pypiCommand, 'pip-quick')}
                    className="text-xs text-blue-400 hover:text-blue-300 font-mono flex items-center space-x-1"
                  >
                    {copiedKey === 'pip-quick' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    <span>Copy</span>
                  </button>
                </div>

                <div className="bg-slate-950 rounded-xl p-4 font-mono text-sm text-emerald-400 border border-slate-800">
                  {selectedModule.pypiCommand}
                </div>
                <p className="text-xs text-slate-400">
                  Installs official package from Python Package Index (PyPI) with zero external dependencies required for core functionality.
                </p>
              </div>

              {/* Cursor / Claude Desktop Execution */}
              <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-3">
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300 font-mono flex items-center gap-2">
                  <Zap className="w-4 h-4 text-amber-400" />
                  2. Direct Execution with uvx (Zero-Install)
                </h3>

                <div className="bg-slate-950 rounded-xl p-4 font-mono text-sm text-cyan-300 border border-slate-800 flex items-center justify-between">
                  <span>uvx {selectedModule.pypiPackage}</span>
                  <button
                    onClick={() => handleCopy(`uvx ${selectedModule.pypiPackage}`, 'uvx-cmd')}
                    className="text-slate-400 hover:text-white"
                  >
                    {copiedKey === 'uvx-cmd' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  </button>
                </div>
                <p className="text-xs text-slate-400">
                  Executes automatically in an isolated ephemeral environment. Ideal for Claude Desktop, Cursor AI, and continuous integration pipelines.
                </p>
              </div>
            </div>
          )}

          {/* TAB 2: Tools Spec */}
          {activeTab === 'tools' && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-bold text-white font-mono flex items-center gap-2">
                  <Cpu className="w-4 h-4 text-blue-400" />
                  Defined MCP Tools ({selectedModule.tools.length})
                </h3>
                <span className="text-xs text-slate-400 font-mono">Standard JSON-RPC 2.0 interface</span>
              </div>

              <div className="space-y-4">
                {selectedModule.tools.map((tool, idx) => (
                  <div key={tool.name} className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-3">
                    <div className="flex items-center justify-between border-b border-slate-800/80 pb-3">
                      <div className="flex items-center space-x-2">
                        <span className="text-xs font-mono text-slate-500">#{idx + 1}</span>
                        <code className="text-sm font-bold font-mono text-emerald-400">{tool.name}</code>
                      </div>
                      <button
                        onClick={() => handleCopy(tool.name, `tool-${tool.name}`)}
                        className="text-xs text-slate-400 hover:text-white font-mono flex items-center space-x-1"
                      >
                        {copiedKey === `tool-${tool.name}` ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                        <span>Copy Name</span>
                      </button>
                    </div>

                    <p className="text-xs text-slate-300 leading-relaxed">
                      {tool.description}
                    </p>

                    <div className="space-y-1.5 pt-1">
                      <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider block">Sample Input Payload:</span>
                      <pre className="bg-slate-950 p-3 rounded-xl border border-slate-800 text-xs font-mono text-cyan-300 overflow-x-auto">
                        {tool.sampleInput}
                      </pre>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* TAB 3: JSON-RPC Config */}
          {activeTab === 'config' && (
            <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300 font-mono flex items-center gap-2">
                  <FileCode2 className="w-4 h-4 text-violet-400" />
                  Claude Desktop & Cursor Config Snippet
                </h3>
                <button
                  onClick={() => handleCopy(claudeConfigJson, 'json-cfg')}
                  className="px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-mono font-bold transition-all flex items-center space-x-1.5"
                >
                  {copiedKey === 'json-cfg' ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>Copy Configuration</span>
                </button>
              </div>

              <pre className="bg-slate-950 p-4 rounded-xl border border-slate-800 text-xs font-mono text-slate-200 overflow-x-auto leading-relaxed">
                {claudeConfigJson}
              </pre>

              <p className="text-xs text-slate-400">
                Paste this block into your <code className="text-cyan-300">claude_desktop_config.json</code> file located at <code className="text-slate-300">~/.config/Claude/claude_desktop_config.json</code> or Cursor MCP settings tab.
              </p>
            </div>
          )}

          {/* TAB 4: Dedicated Module Edge Gateway */}
          {activeTab === 'edge' && (
            <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-4">
              <div className="flex items-center space-x-2 text-emerald-400 font-bold font-mono text-sm">
                <Globe className="w-4 h-4" />
                <span>Exact Configured Edge Gateway Topology</span>
              </div>

              <p className="text-xs text-slate-300 leading-relaxed">
                This MCP module runs on its dedicated edge worker gateway at <strong className="text-amber-300">{selectedModule.edgeGateway}</strong> with low-latency SSE streaming.
              </p>

              <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-2 font-mono text-xs">
                <div className="flex items-center justify-between text-slate-400">
                  <span>Exact Gateway Host:</span>
                  <span className="text-amber-300 font-bold">{selectedModule.edgeGateway}</span>
                </div>
                <div className="flex items-center justify-between text-slate-400">
                  <span>Exact Gateway SSE URL:</span>
                  <span className="text-emerald-400 font-bold">{selectedModule.edgeUrl}</span>
                </div>
                <div className="flex items-center justify-between text-slate-400">
                  <span>Central Developer Portal:</span>
                  <span className="text-cyan-300">{DEVELOPERS_SUBDOMAIN}</span>
                </div>
                <div className="flex items-center justify-between text-slate-400">
                  <span>Official Support Email:</span>
                  <span className="text-blue-400">{OFFICIAL_CORPORATE_EMAIL}</span>
                </div>
              </div>
            </div>
          )}

          {/* TAB 5: 10 Official Cloudflare Edge Gateways Directory */}
          {activeTab === 'gateways' && (
            <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-6">
              <div className="flex items-center justify-between border-b border-slate-800 pb-4">
                <div className="space-y-1">
                  <div className="flex items-center space-x-2">
                    <span className="px-2.5 py-0.5 rounded-full text-xs font-mono font-bold bg-amber-500/10 border border-amber-500/30 text-amber-400 flex items-center gap-1.5">
                      <Globe className="w-3.5 h-3.5" />
                      Cloudflare Edge Network
                    </span>
                    <span className="text-xs font-mono text-emerald-400 font-bold">10 Live Gateways</span>
                  </div>
                  <h3 className="text-lg font-extrabold text-white">
                    Official SEOSiri Cloudflare Edge Gateways (*.seosiri.com)
                  </h3>
                </div>
              </div>

              <div className="overflow-x-auto rounded-xl border border-slate-800">
                <table className="w-full text-left text-xs font-mono">
                  <thead className="bg-slate-950 text-slate-400 border-b border-slate-800 uppercase tracking-wider text-[11px]">
                    <tr>
                      <th className="py-3 px-4">#</th>
                      <th className="py-3 px-4">Edge Subdomain Gateway</th>
                      <th className="py-3 px-4">Health Check Endpoint</th>
                      <th className="py-3 px-4">Target MCP Server / Repo</th>
                      <th className="py-3 px-4">Purpose / Domain</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-800/60 bg-slate-900/50">
                    {OFFICIAL_EDGE_GATEWAYS.map((gw) => (
                      <tr key={gw.id} className="hover:bg-slate-800/40 transition-colors">
                        <td className="py-3 px-4 font-bold text-slate-500">{gw.id}</td>
                        <td className="py-3 px-4">
                          <code className="text-amber-300 font-bold bg-slate-950 px-2 py-1 rounded border border-slate-800">
                            {gw.subdomain}
                          </code>
                        </td>
                        <td className="py-3 px-4">
                          <a
                            href={gw.healthEndpoint}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-emerald-400 hover:underline flex items-center gap-1"
                          >
                            <span>{gw.healthEndpoint}</span>
                            <ExternalLink className="w-3 h-3 text-slate-500" />
                          </a>
                        </td>
                        <td className="py-3 px-4 font-semibold text-blue-300">
                          {gw.targetMcpServer}
                        </td>
                        <td className="py-3 px-4 text-slate-300 font-sans text-xs">
                          {gw.purpose}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Operational characteristics info box */}
              <div className="bg-slate-950 p-4 rounded-xl border border-slate-800/80 space-y-2 text-xs text-slate-300 font-sans">
                <h4 className="font-bold text-white font-mono flex items-center gap-2">
                  <Info className="w-4 h-4 text-blue-400" />
                  Gateway Operational Characteristics:
                </h4>
                <ul className="list-disc list-inside space-y-1 text-slate-400">
                  <li><strong className="text-slate-200">Protocol & Transport:</strong> Server-Sent Events (SSE) and JSON-RPC 2.0 over HTTPS.</li>
                  <li><strong className="text-slate-200">Smart Browser Handling:</strong> Human visitors entering any gateway URL in a web browser are cleanly redirected (HTTP 301) to their corresponding technical article on seosiri.com.</li>
                  <li><strong className="text-slate-200">AI Agent Health Checks:</strong> AI clients querying <code className="text-emerald-300 font-mono">/health</code> on any edge domain receive an instant 200 OK - HEALTHY JSON response.</li>
                  <li><strong className="text-slate-200">CORS & Zero Trust:</strong> Pre-configured with universal CORS headers (<code className="text-cyan-300 font-mono">Access-Control-Allow-Origin: *</code>) for remote AI agent execution.</li>
                </ul>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
